---
title: "EconomyAnalysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
```

## Instalacja bibliotek
```{r cache=TRUE}
r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)
install.packages("readxl")
```
```{r}
library("readxl")
library(dplyr)
library(tidyr)
library(ggplot2)
library(mlbench)
library(caret)
```

## Wczytanie danych z pliku

Ścieżka do folderu z danymi

```{r savePath}
dataDirectoryPath <- 'C:/Users/anna/OneDrive/Nauka/II semestr II stopień/Zaawansowana Eksploracja Danych/Data pack/Data pack/'
```

Wczytanie pliku CurrencyExchangeRates.csv

```{r}
currencyExchangeRatesPath <- paste0(dataDirectoryPath, 'CurrencyExchangeRates.csv')
currencyExchangeRates <- read.csv(currencyExchangeRatesPath)
```

Wczytanie pliku Gold prices.csv

```{r}
goldPricesPath <- paste0(dataDirectoryPath, 'Gold prices.csv')
goldPrices <- read.csv(goldPricesPath)
```

Wczytanie pliku S&P Composite.csv

```{r}
spCompositePath <- paste0(dataDirectoryPath, 'S&P Composite.csv')
spComposite <- read.csv(spCompositePath)
```

Wczytanie pliku World_Development_Indicators.xlsx
```{r}
worldDevelopmentIndicatorsPath <- paste0(dataDirectoryPath, 'World_Development_Indicators.xlsx')
worldDevelopmentIndicators <- read_excel(worldDevelopmentIndicatorsPath)
```

## Podsumowanie danych 

```{r summary}
knitr::kable(summary(worldDevelopmentIndicators))
knitr::kable(head(worldDevelopmentIndicators))
```

## Czyszczenie danych

```{r clean dataset}
cleanedWorldDevelopmentIndicators <- worldDevelopmentIndicators[1:42600,]
cleanedWorldDevelopmentIndicators <- cleanedWorldDevelopmentIndicators %>% 
  mutate_at(vars(!c('Country Name', 'Country Code', 'Series Name', 'Series Code')), as.numeric) %>%
  pivot_longer(!c('Country Name', 'Country Code', 'Series Name', 'Series Code'), names_to = "year", values_to="value")
knitr::kable(head(cleanedWorldDevelopmentIndicators))

cleanedWorldDevelopmentIndicatorsResult <- cleanedWorldDevelopmentIndicators %>% 
  pivot_wider(names_from = c('Series Name', 'Series Code'), values_from = 'value',  names_glue = "{`Series Name`}") %>%
  mutate_at(vars(year), as.factor)

```

### Szukanie najlepszych features
```{r best_features}
correlationMatrix <- cor(cleanedWorldDevelopmentIndicatorsResult[,4:211],use="pairwise.complete.obs")
correlationMatrix<-correlationMatrix[,colSums(is.na(correlationMatrix))==0]
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.5)
highlyCorrelated = sort(highlyCorrelated)
reduced_Data = cleanedWorldDevelopmentIndicatorsResult[,-c(highlyCorrelated)]
knitr::kable(head(reduced_Data))

```

## GDP 
```{r}
ggplot(
  cleanedWorldDevelopmentIndicatorsResult, 
  aes(x=year, 
      y=`Trade (% of GDP)`,
      group=1)
) +
geom_line() +
facet_grid(`Country Name` ~ .)
```